// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: test/demo.proto

package demo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_test_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_test_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           string                 `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_test_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *UserRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           string                 `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex           string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_test_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *UserResponse) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetArticlesReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Title    string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Page     int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 作者ID
	// @gotags: form:"author_id" uri:"author_id"
	AuthorId      int32 `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty" form:"author_id" uri:"author_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesReq) Reset() {
	*x = GetArticlesReq{}
	mi := &file_test_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesReq) ProtoMessage() {}

func (x *GetArticlesReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesReq.ProtoReflect.Descriptor instead.
func (*GetArticlesReq) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticlesReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetArticlesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticlesReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetArticlesReq) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type GetArticlesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Articles      []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResp) Reset() {
	*x = GetArticlesResp{}
	mi := &file_test_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResp) ProtoMessage() {}

func (x *GetArticlesResp) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResp.ProtoReflect.Descriptor instead.
func (*GetArticlesResp) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticlesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetArticlesResp) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type Article struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Title   string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// @gotags: form:"author_id" uri:"author_id"
	AuthorId      int32 `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty" form:"author_id" uri:"author_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_test_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_test_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_test_demo_proto_rawDescGZIP(), []int{6}
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

var File_test_demo_proto protoreflect.FileDescriptor

const file_test_demo_proto_rawDesc = "" +
	"\n" +
	"\x0ftest/demo.proto\x12\x04demo\x1a\x1cgoogle/api/annotations.proto\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"E\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\tR\x03age\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\"\\\n" +
	"\fUserResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\tR\x03age\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\tR\x03sex\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"t\n" +
	"\x0eGetArticlesReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x05R\bauthorId\"R\n" +
	"\x0fGetArticlesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\barticles\x18\x02 \x03(\v2\r.demo.ArticleR\barticles\"V\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x05R\bauthorId2L\n" +
	"\x04Demo\x12D\n" +
	"\x04Ping\x12\r.demo.Request\x1a\x0e.demo.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/grpcDemo/ping2S\n" +
	"\x04User\x12K\n" +
	"\x03Get\x12\x11.demo.UserRequest\x1a\x12.demo.UserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/grpcDemo/ping2\xdd\x01\n" +
	"\vBlogService\x12s\n" +
	"\vGetArticles\x12\x14.demo.GetArticlesReq\x1a\x15.demo.GetArticlesResp\"7\x82\xd3\xe4\x93\x021Z!\x12\x1f/v1/author/{author_id}/articles\x12\f/v1/articles\x12Y\n" +
	"\rCreateArticle\x12\r.demo.Article\x1a\r.demo.Article\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/author/{author_id}/articlesB\bZ\x06./demob\x06proto3"

var (
	file_test_demo_proto_rawDescOnce sync.Once
	file_test_demo_proto_rawDescData []byte
)

func file_test_demo_proto_rawDescGZIP() []byte {
	file_test_demo_proto_rawDescOnce.Do(func() {
		file_test_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_demo_proto_rawDesc), len(file_test_demo_proto_rawDesc)))
	})
	return file_test_demo_proto_rawDescData
}

var file_test_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_test_demo_proto_goTypes = []any{
	(*Request)(nil),         // 0: demo.Request
	(*Response)(nil),        // 1: demo.Response
	(*UserRequest)(nil),     // 2: demo.UserRequest
	(*UserResponse)(nil),    // 3: demo.UserResponse
	(*GetArticlesReq)(nil),  // 4: demo.GetArticlesReq
	(*GetArticlesResp)(nil), // 5: demo.GetArticlesResp
	(*Article)(nil),         // 6: demo.Article
}
var file_test_demo_proto_depIdxs = []int32{
	6, // 0: demo.GetArticlesResp.articles:type_name -> demo.Article
	0, // 1: demo.Demo.Ping:input_type -> demo.Request
	2, // 2: demo.User.Get:input_type -> demo.UserRequest
	4, // 3: demo.BlogService.GetArticles:input_type -> demo.GetArticlesReq
	6, // 4: demo.BlogService.CreateArticle:input_type -> demo.Article
	1, // 5: demo.Demo.Ping:output_type -> demo.Response
	3, // 6: demo.User.Get:output_type -> demo.UserResponse
	5, // 7: demo.BlogService.GetArticles:output_type -> demo.GetArticlesResp
	6, // 8: demo.BlogService.CreateArticle:output_type -> demo.Article
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_demo_proto_init() }
func file_test_demo_proto_init() {
	if File_test_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_demo_proto_rawDesc), len(file_test_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_test_demo_proto_goTypes,
		DependencyIndexes: file_test_demo_proto_depIdxs,
		MessageInfos:      file_test_demo_proto_msgTypes,
	}.Build()
	File_test_demo_proto = out.File
	file_test_demo_proto_goTypes = nil
	file_test_demo_proto_depIdxs = nil
}
